import { Geist, Geist_Mono } from "next/font/google";
import { Edu_VIC_WA_NT_Beginner } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const eduVic = Edu_VIC_WA_NT_Beginner({
  variable: "--font-edu-vic",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // choose available weights
});

export const metadata = {
  title: "nomadic",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${eduVic.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
